agents/urls.py
from django.urls import path
from . import views

app_name = 'agents'

urlpatterns = [
    path('', views.AgentListView.as_view(), name='list'),
    path('create/', views.AgentCreateView.as_view(), name='create'),
    path('detail/<int:pk>/', views.AgentDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.AgentUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.AgentDeleteView.as_view(), name='delete'),
]

leads/urls.py
from . import views
from django.urls import path

app_name = 'leads'

urlpatterns = [
    path('', views.LandingPageView.as_view(), name='landing'),

    path('leads/', views.LeadListView.as_view(), name='list'),
    path('leads/create/', views.LeadCreateView.as_view(), name='create'),
    path('leads/detail/<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('leads/update/<int:pk>/', views.LeadUpdateView.as_view(), name='update'),
    path('leads/delete/<int:pk>/', views.LeadDeleteView.as_view(), name='delete'),
    
    path('leads/assign_agent/<int:pk>/', views.AssignAgentUpdateView.as_view(), name='assign'),

    path('leads/categories/', views.CategoryListView.as_view(), name='category_list'),    
    path('leads/category_detail/<int:pk>/', views.CategoryDetailView.as_view(), name='category_detail'),
    path('leads/category_update/<int:pk>', views.LeadCategoryUpdateView.as_view(), name='category_update'),    
]

organizorhub/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView)#check source code for template names
from leads.views import SignupView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('leads.urls')),  # Include the leads app's URLconf
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('agents/', include('agents.urls')),

    path('reset_password/', PasswordResetView.as_view(), name='reset_password'),#tip: django prio/defaults its own temp so explictly add your app temp dir in setting.py
    path('password_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),#it comes with default url and name pattern
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),#both kwargs here are necessary
    path('password_resset_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]


# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator



class User(AbstractUser):
    #userprofile : this attribute exists/accessible technically because of the OneToMany bi diretional nature
    #agent : same reason
    is_organizor = models.BooleanField(default=True)#organizors(yes it is miss spelled too late now haha) can see and manage agents and leads
    is_agent = models.BooleanField(default=False)#agents who are not organizors can read leads only



class UserProfile(models.Model):
    '''Model definition for UserProfile.'''
    user = models.OneToOneField(User, on_delete=models.CASCADE)#now both this class and User can access each other

    class Meta:
        '''Meta definition for UserProfile.'''

        verbose_name = 'UserProfile'
        verbose_name_plural = 'UserProfiles'

    def __str__(self):
        return self.user.email
    




class Lead(models.Model):
    '''Model definition for Lead.'''
    first_name = models.CharField(null=False, blank=False, max_length=50)
    last_name = models.CharField(null=False, blank=False, max_length=50)  
    age = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    email = models.EmailField(blank=True,null=True, max_length=254)
    description = models.TextField(blank=True,null=True,)
    date_added = models.DateField(blank=True,null=True,auto_now_add=True)
    phone_number = models.CharField(blank=True, null=True, max_length=8)
    
    agent = models.ForeignKey("Agent",null=True, blank=True, on_delete=models.SET_NULL)#when a related agent is gone its leads remain but his fk is sset to null
    organization =  models.ForeignKey(UserProfile, on_delete=models.CASCADE)#to keep track since agent is nullable
    category = models.ForeignKey("Category",null=True, blank=True, on_delete=models.SET_NULL)


    class Meta:
        verbose_name = 'Lead'
        verbose_name_plural = 'Leads'

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    """     def fix_age(self):
            '''Ensure age is not negative.'''
            if self.age < 0:
                self.age = 0

        def save(self, *args, **kwargs):
            '''Override the save method to fix age before saving.'''
            self.fix_age()
            super().save(*args, **kwargs) """



class Agent(models.Model):
    '''Model definition for Agent.'''
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organization =  models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Agent'
        verbose_name_plural = 'Agents'

    def __str__(self):
        return self.user.username
    

#to automate the creation of a OneToOne userprofile when a user instance is created
def post_user_created_signal(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
        print(f'userprofile(organisation) named {instance.username} has been created')


post_save.connect(post_user_created_signal, sender=User)# when an instance of user model is saved  method gets triggered



class Category(models.Model):
    '''Model definition for Category.'''
    name = models.CharField(max_length=50)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    class Meta:
        '''Meta definition for Category.'''

        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
       return self.name
    

leads/forms.py
from .models import Lead, Agent
from django.contrib.auth import get_user_model
from django import forms

from django.contrib.auth.forms import UserCreationForm


# Get the current active user model dynamically for our login form
User = get_user_model()

class CustomUserCreationForm(UserCreationForm):
    
    class Meta:
        model = User  # Use the dynamically fetched user model
        fields = ('username','email')

    def clean_email(self):
        email = self.cleaned_data.get('email')

        # Ensuring the email is unique (similar to unique=True)
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("A user with this email already exists.")
        
        return email


class LeadForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ('first_name', 'last_name','email','phone_number', 'age', 'agent', 'organization')



class LeadCategorForm(forms.ModelForm):    

    class Meta:
        model = Lead
        fields = ('category',)


        

"""
class AssignAgentForm(forms.Form):    
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")        
        agents = Agent.objects.filter(organization=request.user.userprofile)
        
        super().__init__(*args, **kwargs)#initialize the form

        self.fields["agent"].queryset = agents

"""

"""
removed because in this context we can use ModelForms
class LeadForm(forms.Form):
    first_name = forms.CharField( )
    last_name = forms.CharField()
    age = forms.IntegerField(min_value=18 ,required=False)
"""

leads/views.py
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import *
from .forms import LeadForm, CustomUserCreationForm, LeadCategorForm
from django.views import generic

from django.core.mail import send_mail

from django.contrib.auth.mixins import LoginRequiredMixin
from agents.mixins import OroganizorRequiredMixin#accesible to authenticated and is_organizor = True



class SignupView(generic.CreateView):
    template_name = 'registration/signup.html'
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse('login')


class LandingPageView(generic.TemplateView):
    template_name = 'leads/landing.html'



class LeadListView(LoginRequiredMixin, generic.ListView):
    model_name = Lead
    template_name = 'leads/lead_list.html'
    #queryset constant is only for simple fetching that require no pk or request. or self. we override it
    context_object_name = "leads"
    
    def get_queryset(self):
        user = self.request.user
        #initial queryset based on  role (basically filter for both where a lead has an agent assifned to it)
        if user.is_organizor:#not every organizor is an agent
            queryset = Lead.objects.filter(organization=user.userprofile,agent__isnull=False)# this filters the organizor's leads that belogn only to its organization
        
        elif user.is_agent:
            queryset = Lead.objects.filter(organization=user.agent.organization, agent__isnull=False)#cuz every agent has an org
            #show only leads assigned to the respective agent.
            queryset =  Lead.objects.filter(agent__user=user)
        
        return queryset
    
    def get_context_data(self, **kwargs):        
        context = super().get_context_data(**kwargs)#grab the existing context if any
        user = self.request.user
        if user.is_organizor:
            queryset = Lead.objects.filter(organization=user.userprofile, agent__isnull=True)#to list agentless leads
            context.update({
                "unassigned_leads": queryset
            })
        return context
            
        


class LeadDetailView(LoginRequiredMixin, generic.DetailView):
    model_name = Lead
    template_name = 'leads/lead_detail.html'

    def get_queryset(self):
        user = self.request.user
        #initial queryset based on
        if user.is_organizor:
            queryset = Lead.objects.filter(organization=user.userprofile)#not every organizor is an agent
        
        elif user.is_agent:
            queryset = Lead.objects.filter(organization=user.agent.organization)#cuz every agent has an org
            #show only leads assigned to the respective agent.
            queryset =  Lead.objects.filter(agent__user=user)
        
        return queryset
            
    
   

class LeadCreateView(OroganizorRequiredMixin, generic.CreateView):
    model = Lead
    template_name = 'leads/lead_create.html'
    form_class = LeadForm

    def form_valid(self, form):
        # Save the form (i.e., save the lead to the database) no matter what
        response = super().form_valid(form)
        from django.contrib import messages  # To show a message if email fails
        # Attempt to send an email, but don't let failure stop the lead from being saved
        try:
            send_mail(
                subject="-----A new lead has been created just now----",
                message="Check it out now on the website",
                from_email="your@boss.com",
                recipient_list=["employee@test.com"]
            )
        except ConnectionRefusedError:
            # Handle the email sending failure gracefully
            messages.error(self.request, 'Could not send the email. Lead saved, but please check email server.')

        # Return the response, ensuring the form is processed and user is redirected
        return response
    

    def get_success_url(self):
        return reverse('leads:list')




class LeadUpdateView(OroganizorRequiredMixin, generic.UpdateView):
    model = Lead
    template_name = 'leads/lead_update.html'
    form_class = LeadForm

    def get_queryset(self):
        user = self.request.user    
          
        return Lead.objects.filter(organization=user.userprofile)# this filters the organizor's leads that belogn only to its organization 
            

    def get_success_url(self):
        return reverse('leads:detail', kwargs={'pk': self.object.pk})
    



class LeadDeleteView(OroganizorRequiredMixin, generic.DeleteView):
    model = Lead
    template_name = 'leads/lead_delete.html'

    def get_queryset(self):
        user = self.request.user        
        return Lead.objects.filter(organization=user.userprofile)# this filters the organizor's leads that belogn only to its organization 
            
    
    def get_success_url(self):
        return reverse ('leads:list')
    



class AssignAgentUpdateView(OroganizorRequiredMixin, generic.UpdateView):
    model = Lead  # Assuming Lead model has an 'agent' ForeignKey field
    fields = ['agent']  # The field you're updating
    template_name = 'leads/lead_assign_agent.html'

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        # Filter agents based on the organization of the current user
        form.fields['agent'].queryset = Agent.objects.filter(organization=self.request.user.userprofile)
        return form

    def get_success_url(self) -> str:
        return reverse('leads:list')



#same drill as LeadListView with few changes
class CategoryListView(OroganizorRequiredMixin, generic.ListView):
    
    template_name = 'leads/category_list.html'
    context_object_name = 'categories'
        
    def get_queryset(self):
        user = self.request.user
        
        if user.is_organizor:
            queryset = Category.objects.filter(organization=user.userprofile)
        
        elif user.is_agent:
            queryset = Category.objects.filter(organization=user.agent.organization)          
                    
        return queryset
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        
        if user.is_organizor:
            queryset = Lead.objects.filter(organization=user.userprofile)
        
        elif user.is_agent:
            queryset = Lead.objects.filter(organization=user.agent.organization)          
        
        context.update({
            'unassigned_lead_count' : queryset.filter(category__isnull=True).count()
             
        })
        return context
    
   


class CategoryDetailView(OroganizorRequiredMixin, generic.DetailView):
    model = Category
    template_name = 'leads/category_detail.html'
    context_object_name = 'category'

    def get_queryset(self):
        user = self.request.user
        
        if user.is_organizor:
            queryset = Category.objects.filter(organization=user.userprofile)
        elif user.is_agent:
            queryset = Category.objects.filter(organization=user.agent.organization)
        
        return queryset
    
    # fk is biderectional 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        category = self.get_object()
        
        #leads = Lead.objects.filter(category= self.get_object())# alternatively since we have fk : 
        leads = category.lead_set.all()  
        context.update({
            'leads': leads
        })

        return context




class LeadCategoryUpdateView(OroganizorRequiredMixin, generic.UpdateView):
    model = Category
    template_name = 'leads/category_update.html'
    form_class = LeadCategorForm

    def get_queryset(self):
        user = self.request.user
        
        if user.is_organizor:
            queryset = Lead.objects.filter(organization=user.userprofile)
        
        elif user.is_agent:
            queryset = Lead.objects.filter(organization=user.agent.organization)
            
            queryset =  Lead.objects.filter(agent__user=user)
        
        return queryset
            
    def get_success_url(self):
        return reverse('leads:detail', kwargs={'pk': self.object.pk})




""" 

def landing_page(request):
    return render(request, 'leads/landing.html')

def lead_list(request):
    leads = Lead.objects.all()
    return render(request, 'leads/lead_list.html',{'leads': leads,})


def lead_detail(request, pk):
    lead = Lead.objects.get(pk=pk)#.filter returns a query set .get returns 1 object

    return render(request, 'leads/lead_detail.html', {'lead': lead})


def lead_create(request):
    if request.method == 'POST':
        form = LeadForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('leads:list')    # After successful submit, return home
    else:#if get request just render empty form
        form = LeadForm()
    
    return render(request, 'leads/lead_create.html', {'form': form})


def lead_update(request, pk):
    lead = Lead.objects.get(pk=pk)
    
    if request.method == 'POST':
        form = LeadForm(request.POST, instance=lead)
        if form.is_valid():
            form.save()
            return redirect('leads:list')
    else:
        form = LeadForm(instance=lead)  # Populate the form with existing data
    
    return render(request, 'leads/lead_update.html', {'lead': lead, 'form': form})


def lead_delete(request, pk):
    lead = Lead.objects.get(id=pk)
    lead.delete()
    return redirect('leads:list')
"""   

leads/templates/leads/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    DJCRM/{% block title %}{% endblock title %}
  </title>
  {% block extra_head %}{% endblock extra_head %}

  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <script src="{% static 'js/scripts.js' %}"></script>

</head>


<body>
  {% include 'leads/navbar.html' %}

  <main class="bg-gray-50 flex justify-center items-center min-h-[90vh] m-0 py-8 ">
    {% block content %}

    {% endblock content %}
  </main>

</body>

</html>

leads/templates/leads/category_update.html
{% extends 'leads/base.html' %}

{% block content %}

<style>
    h1 {
        color: #333;
    }

    h5 {
        color: #666;
        margin-bottom: 20px;
    }

    form p {
        margin-bottom: 15px;
    }

    label {
        font-weight: bold;
        display: block;
    }

    input {
        width: 100%;
        padding: 8px;
        margin-top: 5px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    input:focus {
        background: rgba(107, 238, 159, 0.1);

    }
</style>


<section class="text-gray-600 body-font overflow-hidden min-w-[93.3333%]">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">OrganizorHub / Lead</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4"> {{lead.first_name}} {{lead.last_name}}
                </h1>
                <div class="flex mb-4">
                    <a href="{% url 'leads:detail' lead.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Status</a>
                    <a href="{% url 'leads:category_update' lead.pk %}"
                        class="flex-grow text-green-500 border-b-2 border-green-500 py-2 text-lg px-1">Status</a>
                    <a href="{% url 'leads:update' lead.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update
                        Details
                    </a>

                </div>


                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button
                        class=" w-10/12 -mb-3 flex self-center bg-blue-700 hover:bg-blue-300 rounded text-white font-bold py-2 px-4 ">
                        Submit
                    </button>
                </form>



            </div>
            <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
                src="https://dummyimage.com/400x400">
        </div>
        <a href="{% url 'leads:delete' lead.pk %}"
            class=" w-1/5 mt-3 ml-auto  flex self-center bg-red-700 hover:bg-red-300 rounded text-white font-bold py-2 px-4 text-center ">Delete</a>
    </div>
</section>



<script>
    // Save scroll position before the page unloads
    window.addEventListener("beforeunload", function () {
        const currentScrollPosition = window.scrollY;
        const storedScrollPosition = localStorage.getItem("scrollPosition");

        // Only set the item if the current position is different from the stored position
        if (storedScrollPosition !== null && parseInt(storedScrollPosition, 10) !== currentScrollPosition) {
            localStorage.setItem("scrollPosition", currentScrollPosition);
        } else if (storedScrollPosition === null) {
            // If no scroll position is stored, set it
            localStorage.setItem("scrollPosition", currentScrollPosition);
        }
    });

    // Restore scroll position once the DOM content is loaded
    document.addEventListener("DOMContentLoaded", function () {
        const scrollPosition = localStorage.getItem("scrollPosition");
        if (scrollPosition) {
            window.scrollTo(0, parseInt(scrollPosition, 10));
        }
    });

</script>


{% endblock %}

leads/templates/leads/landing.html
{% extends 'leads/base.html' %}
{% load static %}
{% block content %}

<section class="text-gray-600 body-font"></section>
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="{% static 'images/landing_image.png' %}">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">OrganizorHub</h1>
        <p class="mb-8 leading-relaxed">
          this is a crm helps you manage ur leads  
        </p>
        <div class="flex justify-center">
          <a href="{% url 'agents:list' %}" class="inline-flex text-white bg-green-500 border-0 py-2 px-6 focus:outline-none hover:bg-green-600 rounded text-lg">Agents</a>
          <a href="{% url 'leads:list' %}" class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">Leads</a>
        </div>
      </div>
    </div>
</section> 

{% endblock content %}

leads/templates/leads/lead_detail.html
{% extends 'leads/base.html' %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">OrganizorHub / Lead</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4"> {{lead.first_name}} {{lead.last_name}} </h1>
          <div class="flex mb-4">

            <a href="{% url 'leads:detail' lead.pk %}" class="flex-grow text-green-500 border-b-2 border-green-500 py-2 text-lg px-1">
              Overview
            </a>

            <a href="{% url 'leads:category_update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
              Status
            </a>

            <a  href="{% url 'leads:update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
              Update Details
            </a>
            
          </div>
          <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Age</span>
            <span class="ml-auto text-gray-900"> {{lead.age}} </span>
          </div>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Location</span>
            <span class="ml-auto text-gray-900">Groove Street (home)</span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-200 py-2">
            <span class="text-gray-500">Status</span>
            <span class="ml-auto text-gray-900">{{lead.category}}</span>
          </div>
         
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
</section>



<script>
// Save scroll position before the page unloads
window.addEventListener("beforeunload", function() {
    const currentScrollPosition = window.scrollY;
    const storedScrollPosition = localStorage.getItem("scrollPosition");

    // Only set the item if the current position is different from the stored position
    if (storedScrollPosition !== null && parseInt(storedScrollPosition, 10) !== currentScrollPosition) {
        localStorage.setItem("scrollPosition", currentScrollPosition);
    } else if (storedScrollPosition === null) {
        // If no scroll position is stored, set it
        localStorage.setItem("scrollPosition", currentScrollPosition);
    }
});

// Restore scroll position once the DOM content is loaded
document.addEventListener("DOMContentLoaded", function() {
    const scrollPosition = localStorage.getItem("scrollPosition");
    if (scrollPosition) {
        window.scrollTo(0, parseInt(scrollPosition, 10));
    }
});

</script>

{% endblock %}

leads/templates/leads/lead_update.html
{% extends 'leads/base.html' %}

{% block content %}

<style>
    h1 {
        color: #333;
    }

    h5 {
        color: #666;
        margin-bottom: 20px;
    }

    form p {
        margin-bottom: 15px;
    }

    label {
        font-weight: bold;
        display: block;
    }

    input {
        width: 100%;
        padding: 8px;
        margin-top: 5px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    input:focus {
        background: rgba(107, 238, 159, 0.1);

    }
</style>


<section class="text-gray-600 body-font overflow-hidden min-w-[93.3333%]">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">OrganizorHub / Lead</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4"> {{lead.first_name}} {{lead.last_name}}
                </h1>
                <div class="flex mb-4">
                    <a href="{% url 'leads:detail' lead.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Status</a>
                    <a href="{% url 'leads:category_update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Status</a>
                    <a href="{% url 'leads:update' lead.pk %}"
                        class="flex-grow text-green-500 border-b-2 border-green-500 py-2 text-lg px-1">Update
                        Details</a>

                </div>


                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button
                        class=" w-10/12 -mb-3 flex self-center bg-blue-700 hover:bg-blue-300 rounded text-white font-bold py-2 px-4 ">
                        Submit
                    </button>
                </form>



            </div>
            <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
                src="https://dummyimage.com/400x400">
        </div>
        <a href="{% url 'leads:delete' lead.pk %}"
            class=" w-1/5 mt-3 ml-auto  flex self-center bg-red-700 hover:bg-red-300 rounded text-white font-bold py-2 px-4 text-center ">Delete</a>
    </div>
</section>



<script>
    // Save scroll position before the page unloads
    window.addEventListener("beforeunload", function () {
        const currentScrollPosition = window.scrollY;
        const storedScrollPosition = localStorage.getItem("scrollPosition");

        // Only set the item if the current position is different from the stored position
        if (storedScrollPosition !== null && parseInt(storedScrollPosition, 10) !== currentScrollPosition) {
            localStorage.setItem("scrollPosition", currentScrollPosition);
        } else if (storedScrollPosition === null) {
            // If no scroll position is stored, set it
            localStorage.setItem("scrollPosition", currentScrollPosition);
        }
    });

    // Restore scroll position once the DOM content is loaded
    document.addEventListener("DOMContentLoaded", function () {
        const scrollPosition = localStorage.getItem("scrollPosition");
        if (scrollPosition) {
            window.scrollTo(0, parseInt(scrollPosition, 10));
        }
    });

</script>


{% endblock %}