agents/urls.py
from django.urls import path
from . import views

app_name = 'agents'

urlpatterns = [
    path('', views.AgentListView.as_view(), name='list'),
    path('create/', views.AgentCreateView.as_view(), name='create'),
    path('detail/<int:pk>/', views.AgentDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.AgentUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.AgentDeleteView.as_view(), name='delete'),
]

leads/urls.py
from . import views
from django.urls import path

app_name = 'leads'

urlpatterns = [
    path('', views.LandingPageView.as_view(), name='landing'),

    path('leads/', views.LeadListView.as_view(), name='list'),
    path('leads/create/', views.LeadCreateView.as_view(), name='create'),
    path('leads/detail/<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('leads/update/<int:pk>/', views.LeadUpdateView.as_view(), name='update'),
    path('leads/delete/<int:pk>/', views.LeadDeleteView.as_view(), name='delete'),
    
    path('leads/assign_agent/<int:pk>/', views.AssignAgentUpdateView.as_view(), name='assign'),

    path('leads/categories/', views.CategoryListView.as_view(), name='category_list'),    
    path('leads/category_detail/<int:pk>/', views.CategoryDetailView.as_view(), name='category_detail'),
    path('leads/category_update/<int:pk>', views.LeadCategoryUpdateView.as_view(), name='category_update'),    
]

organizorhub/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView)#check source code for template names
from leads.views import SignupView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('leads.urls')),  # Include the leads app's URLconf
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('agents/', include('agents.urls')),

    path('reset_password/', PasswordResetView.as_view(), name='reset_password'),#tip: django prio/defaults its own temp so explictly add your app temp dir in setting.py
    path('password_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),#it comes with default url and name pattern
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),#both kwargs here are necessary
    path('password_resset_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]


# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model



User = get_user_model()#our authenticated model


class AgentForm(forms.ModelForm):
    class Meta:
        model = User#this will have implications on the leads.models.User model
        fields = ('username','first_name', 'last_name', 'email')#basically it creates intances of  a User > automatically UserProfile (dj signals) > and with those info manuall Agent (in the view)
        

agents/views.py
#from django.contrib.auth.mixins import LoginRequiredMixin : i made a custom mixin that overrides this

from .mixins import OroganizorRequiredMixin #custom mixin
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.urls import reverse
from django.views import generic
from leads.models import Agent
from .forms import AgentForm

from django.core.mail import send_mail
from django.contrib import messages






class AgentListView(OroganizorRequiredMixin, generic.ListView):
    model = Agent
    template_name = 'agents/agent_list.html'
    context_object_name = 'agents'

    def get_queryset(self):        
        #From User, you can access the UserProfile using .userprofile.
        myrequest_organization = self.request.user.userprofile
        return Agent.objects.filter(organization=myrequest_organization)
    


class AgentCreateView(generic.CreateView):
    model = Agent
    template_name = 'agents/agent_create.html'
    form_class = AgentForm


    #basically it creates intances of  a User > automatically UserProfile (dj signals) > and with those info manuall Agent (in the view)
    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        user = form.save(commit=False)  # Save the form but don't commit to the database yet
        user.is_agent = True
        user.is_organizor = False
        user.set_password("password2strongXD")
        user.save()

        # Create an Agent linked to the User and Organization manually with the newly made User instance 
        Agent.objects.create(user=user, organization=self.request.user.userprofile)
        
        # Attempt to send an email notification to the new agent
        try:
            send_mail(
                subject="---- A new *job* assignment ---",
                message="You have been picked to be the agent, please login with the new credentials",
                from_email="your-boss@test.com",
                recipient_list=[user.email],  # Use the agent's email
            )
        except ConnectionRefusedError:
            messages.error(self.request, 'Could not send the email. Agent saved, but please check email server.')

        return super().form_valid(form)  # Call the parent method to finalize the form submission    

    def get_success_url(self) -> str:
        return reverse("agents:list")  # Redirects to the agent list after creation



class AgentDetailView(OroganizorRequiredMixin, generic.DetailView):
    model = Agent
    template_name = 'agents/agent_detail.html'
    context_object_name = 'agent'
    queryset = Agent.objects.all()



class AgentUpdateView(OroganizorRequiredMixin, generic.UpdateView):
    model = Agent
    template_name = 'agents/agent_update.html'
    form_class = AgentForm

    def get_success_url(self):
        return reverse('agents:detail', kwargs={'pk': self.object.pk})



class AgentDeleteView(generic.DeleteView):
    model = Agent
    template_name = 'agents/agent_delete.html'
    context_object_name = 'agent'

    def get_success_url(self) -> str:
        return reverse('agents:list')

agents/templates/agents/agent_create.html
{% extends 'leads/base.html' %}
{% block content %}
<style>
    main {
        background-color: #e0e5ec;
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 90vh;
        margin: 0;
        padding: 2rem 0;
    }

    #scoping-section h2 {
        color: #333;
        font-size: 1.875rem;
        margin-bottom: 10px;
        text-align: center;
        font-weight: bold;
    }

    #scoping-section h5 {
        color: #666;
        margin-bottom: 20px;
        text-align: center;
    }

    #scoping-section form p {
        margin-bottom: 15px;
    }

    #scoping-section label {
        font-weight: bold;
        display: block;
        margin-bottom: 5px;
    }

    #scoping-section input {
        width: 100%;
        padding: 10px;
        margin-top: 5px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        font-size: 1rem;
    }

    #scoping-section input:focus {
        background: rgba(107, 238, 159, 0.1);
        outline: none;
        border-color: #6bef9f;
    }

    #scoping-section a {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        width: 100%;
        padding: 10px;
        margin-top: 15px;
        background-color: #6bef9f;
        color: white;
        text-decoration: none;
        border-radius: 4px;
        font-size: 1.125rem;
        font-weight: bold;
        transition: background-color 0.3s ease;
    }

    #scoping-section a:hover {
        background-color: #4bc77d;
    }

    #scoping-section a svg {
        margin-left: 10px;
        width: 1.25rem;
        height: 1.25rem;
    }
</style>


<section id="scoping-section" class="min-w-[33.3333%] p-8 mx-auto mt-10 bg-slate-100 rounded-lg drop-shadow-2xl">
    <h2 class="text-center text-lg font-bold mb-4">Create</h2>
    <h5>Fill in the form to create a new agent</h5>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="text-sm text-gray-500"></div>
        <small><em>Note:</em> Creating an agent will subsequently create a user and its respective userprofile <br> | password is default in developement: <code>password2strongXD</code> </small>
        </div>
        <a>
            <button type="submit">Create</button>
        </a>
    </form>
</section>


{% endblock content %}

agents/templates/agents/agent_delete.html
{% extends 'leads/base.html' %}
{% block content %}


<section class="bg-white p-6 rounded-lg shadow-md max-w-lg mx-auto mt-10">
    <h1 class="text-2xl font-bold text-gray-800 mb-4 text-center">Are you sure?</h1>
    <h5 class="text-gray-600 text-center mb-6">
        This Agent "{{ agent.user.username }}" and all of its related leads and profiles will be gone forever!
    </h5>

    <form method="POST" class="space-y-4">
        {% csrf_token %}
        {{ form.as_p }}

        <!-- Delete Button -->
        <div class="flex justify-center space-x-4">
            <button
                class="w-1/3 bg-red-700 hover:bg-red-500 text-white font-bold py-2 px-4 rounded-lg transition duration-300"
                type="submit">
                Delete
            </button>

            <!-- Cancel Button -->
            <a href="{% url 'agents:detail' agent.pk %}"
                class="w-1/3 bg-green-700 hover:bg-green-500 text-white font-bold py-2 px-4 rounded-lg text-center transition duration-300">
                Cancel
            </a>
        </div>
    </form>
</section>

{% endblock content %}

agents/templates/agents/agent_detail.html
{% extends 'leads/base.html' %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">OrganizorHub / Lead</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4"> {{agent.user.username}}
          {{agent.user.first_name}} </h1>
        <div class="flex mb-4">
          <a href="{% url 'agents:detail' agent.pk %}"
            class="flex-grow text-green-500 border-b-2 border-green-500 py-2 text-lg px-1">Overview</a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Reviews</a>
          <a href="{% url 'agents:update' agent.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update Agent Details</a>

        </div>
        <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy
          chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1
          seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Age</span>
          <span class="ml-auto text-gray-900"> {{agent.user.email}} </span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Location</span>
          <span class="ml-auto text-gray-900">Groove Street (home)</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Cell phone</span>
          <span class="ml-auto text-gray-900">+216 54-946-265</span>
        </div>

      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
        src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>



<script>
  // Save scroll position before the page unloads
  window.addEventListener("beforeunload", function () {
    const currentScrollPosition = window.scrollY;
    const storedScrollPosition = localStorage.getItem("scrollPosition");

    // Only set the item if the current position is different from the stored position
    if (storedScrollPosition !== null && parseInt(storedScrollPosition, 10) !== currentScrollPosition) {
      localStorage.setItem("scrollPosition", currentScrollPosition);
    } else if (storedScrollPosition === null) {
      // If no scroll position is stored, set it
      localStorage.setItem("scrollPosition", currentScrollPosition);
    }
  });

  // Restore scroll position once the DOM content is loaded
  document.addEventListener("DOMContentLoaded", function () {
    const scrollPosition = localStorage.getItem("scrollPosition");
    if (scrollPosition) {
      window.scrollTo(0, parseInt(scrollPosition, 10));
    }
  });

</script>

{% endblock %}

agents/templates/agents/agent_list.html
{% extends 'leads/base.html' %}
{% block title %}
Agents
{% endblock title %}


{% block content %}



<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">

        <div class=" w-full flex justify-between mb-6 py-6 border-b border-gray-200  items-center">
            <div>
                <h1 class="text-4xl text-gray-800 ">List of our Agents</h1>
            </div>
            <div>
                <a href="{% url 'agents:create' %}">
                    <h2 class=" p-3 text-white text-xl bg-teal-400 hover:bg-teal-800 rounded">create</h2>
                </a>
            </div>
        </div>


        <div class="flex flex-wrap -m-4">


            {% for a in agents %}

            <div class="p-4 lg:w-1/2 md:w-full">
                <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                    <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-green-100 text-green-500 flex-shrink-0">
                        <svg width="100" height="100" viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg"
                            fill="#000000">
                            <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                            <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                            <g id="SVGRepo_iconCarrier">
                                <defs>
                                    <style>
                                        .cls-1 {
                                            fill: #e0e9ee;
                                        }

                                        .cls-2 {
                                            fill: #d0e1e8;
                                        }

                                        .cls-3 {
                                            fill: #748a95;
                                        }

                                        .cls-4 {
                                            fill: #efc89d;
                                        }
                                    </style>
                                </defs>
                                <g id="Ninja">
                                    <path class="cls-1"
                                        d="M27.11,36.47v6.85l-2.55,1.49s-2.7,3.47-2.18,5.65S26.71,56,26.71,56H37.3s3.82-3.36,4.34-5.54-2.18-5.65-2.18-5.65L36.9,43.32V36.47Z"
                                        id="path123162-1-5-3"></path>
                                    <path class="cls-2"
                                        d="M25.3,48.44a1,1,0,1,0,0,2h3.15a1.3,1.3,0,0,1,1.13.64,1,1,0,0,0,1.36.37h0a1,1,0,0,0,.37-1.37,3.32,3.32,0,0,0-2.86-1.64Z"
                                        id="path132344-1-6-7-9"></path>
                                    <path class="cls-2"
                                        d="M35.56,48.44a3.31,3.31,0,0,0-2.85,1.64,1,1,0,1,0,1.73,1,1.29,1.29,0,0,1,1.12-.64h3.16a1,1,0,0,0,0-2Z"
                                        id="path67681-2"></path>
                                    <path class="cls-1" d="M17.64,49.11,10.51,36.77l4.56-2.64,7,12.13-.22,3.47Z"
                                        id="path92219-8"></path>
                                    <path class="cls-1" d="M46.36,49.1l7.13-12.35-4.56-2.63-7,12.13.22,3.47Z"
                                        id="path92935-0"></path>
                                    <path class="cls-3"
                                        d="M39.46,44.81A104,104,0,0,1,37.3,56H48a1.53,1.53,0,0,0,1.5-1.82c-.58-2.92-2.7-5.07-5.28-6.58Z"
                                        id="path106342-7"></path>
                                    <path class="cls-3"
                                        d="M24.56,44.81,19.78,47.6c-2.57,1.51-4.7,3.66-5.27,6.58A1.52,1.52,0,0,0,16,56H26.71A105.53,105.53,0,0,1,24.56,44.81Z"
                                        id="path63308-3-4"></path>
                                    <path class="cls-3"
                                        d="M43.3,30.2c-2,5.13-6.33,9.67-11.29,9.67s-9.25-4.54-11.3-9.67c-1-2.52-1.19-7-1.19-9.71a12.49,12.49,0,0,1,25,0C44.5,23.22,44.31,27.68,43.3,30.2Z"
                                        id="path25222-7-2-9-4"></path>
                                    <path class="cls-4"
                                        d="M26.53,20.55H37.48a3.39,3.39,0,1,1,0,6.77H26.53a3.39,3.39,0,1,1,0-6.77Z"
                                        id="rect81785-7"></path>
                                    <path class="cls-3"
                                        d="M8.79,31.62l2.66,4.61,2.69-1.56-2.66-4.61a1.55,1.55,0,0,0-2.69,1.56Z"
                                        id="path84599-5"></path>
                                    <path class="cls-3"
                                        d="M55.21,31.61l-2.66,4.6-2.69-1.55,2.66-4.61a1.55,1.55,0,1,1,2.69,1.56Z"
                                        id="path86849-6"></path>
                                    <path class="cls-2"
                                        d="M16.89,32.27a1,1,0,0,0-.76.1L8.46,36.8a1,1,0,0,0-.37,1.36h0a1,1,0,0,0,1.37.37l7.67-4.43a1,1,0,0,0,.36-1.36h0A1,1,0,0,0,16.89,32.27Z"
                                        id="path84380"></path>
                                    <path class="cls-2"
                                        d="M47.11,32.26a1,1,0,0,0-.24,1.83h0l7.67,4.43a1,1,0,1,0,1-1.74h0l-7.67-4.42A1,1,0,0,0,47.11,32.26Z"
                                        id="path86847"></path>
                                </g>
                            </g>
                        </svg>
                    </div>
                    <div class="flex-grow">
                        <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                            {{a.user.username}}
                        </h2>
                        <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast
                            vegan taxidermy. Gastropub indxgo juice poutine.</p>
                        <a href="{% url 'agents:detail' a.pk %}" class="mt-3 text-green-500 inline-flex items-center">
                            Learn More
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                <path d="M5 12h14M12 5l7 7-7 7"></path>
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
            {% empty %}
            <p>No leads assigned to your name.</p>
            {% endfor %}

        </div>


    </div>
</section>



{% if messages %}
<div class="fixed bottom-5 right-5 z-50 space-y-4">
    {% for message in messages %}
    <div
        class="toast {{ message.tags }} bg-gray-800 text-white p-4 rounded-md shadow-lg flex items-center justify-between">
        <span>{{ message }}</span>
        <button onclick="this.parentElement.remove()" class="ml-4 text-gray-400 hover:text-gray-200 focus:outline-none">
            &times;
        </button>
    </div>
    {% endfor %}
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const toasts = document.querySelectorAll('.toast');
        toasts.forEach(toast => {
            setTimeout(() => {
                toast.remove();
            }, 5000); // Disappear after 5 seconds
        });
    });
</script>
{% endif %}




{% endblock content %}

agents/templates/agents/agent_update.html
{% extends 'leads/base.html' %}

{% block content %}

<style>
    h1 {
        color: #333;
    }

    h5 {
        color: #666;
        margin-bottom: 20px;
    }

    form p {
        margin-bottom: 15px;
    }

    label {
        font-weight: bold;
        display: block;
    }

    input {
        width: 100%;
        padding: 8px;
        margin-top: 5px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    input:focus {
        background: rgba(107, 238, 159, 0.1);

    }
</style>

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">DJCRM / Agent</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4"> {{agent.user.username}}
                    {{agent.user.first_name}} </h1>
                <div class="flex mb-4">
                    <a href="{% url 'agents:detail' agent.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Overview</a>
                    <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Reviews</a>
                    <a href="{% url 'agents:update' agent.pk %}"
                        class="flex-grow text-green-500 border-b-2 border-green-500 py-2 text-lg px-1">Update Agent
                        Details</a>

                </div>



                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button
                        class=" w-10/12 -mb-3 flex self-center bg-blue-700 hover:bg-blue-300 rounded text-white font-bold py-2 px-4 ">
                        Submit
                    </button>
                </form>



            </div>
            <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
                src="https://dummyimage.com/400x400">
        </div>
        <a href="{% url 'agents:delete' agent.pk %}"
            class=" w-1/5 mt-3 ml-auto  flex self-center bg-red-700 hover:bg-red-300 rounded text-white font-bold py-2 px-4 text-center ">Delete</a>
    </div>
</section>



<script>
    // Save scroll position before the page unloads
    window.addEventListener("beforeunload", function () {
        const currentScrollPosition = window.scrollY;
        const storedScrollPosition = localStorage.getItem("scrollPosition");

        // Only set the item if the current position is different from the stored position
        if (storedScrollPosition !== null && parseInt(storedScrollPosition, 10) !== currentScrollPosition) {
            localStorage.setItem("scrollPosition", currentScrollPosition);
        } else if (storedScrollPosition === null) {
            // If no scroll position is stored, set it
            localStorage.setItem("scrollPosition", currentScrollPosition);
        }
    });

    // Restore scroll position once the DOM content is loaded
    document.addEventListener("DOMContentLoaded", function () {
        const scrollPosition = localStorage.getItem("scrollPosition");
        if (scrollPosition) {
            window.scrollTo(0, parseInt(scrollPosition, 10));
        }
    });

</script>


{% endblock %}